project:
  type: website
bibliography: references.bib
website:
  title: "GreenTechEngineering"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
  sidebar:
    style: "docked"
    search: true
format:
  html:
    theme: cosmo
    css: styles.css



